### ISSUE TITLE
operator= and copy/move constructor do not consider the ORDERING type

### ISSUE THREAD

**Issue by shirnschall** [shirnschall/DHL-LinAlg#3]
assigning a colMajor Matrix to a rowMajor matrix is not yet considered in operator= and copy/move constructor.

**Comment by erdieee** [comment]
fixed in [3e2d72f](https://github.com/shirnschall/DHL-LinAlg/commit/3e2d72f310cfa60c6d0acc8a7bf9ef841fedca05)
